### PR TITLE
commit on feature-branch

### PR DESCRIPTION
**Pull request by Rishika0101**

### CODE REVIEW

**Review by AnuradhaKumari201 — COMMENTED** [review]
Please use setter and getter method properly.

**Review by AnuradhaKumari201 — COMMENTED** [review]
No need to take input from scanner. 
Kindly remove.

**Review by AnuradhaKumari201 — COMMENTED** [review]
Person Class is the POJO class, Please maintain the sequence and follow the encapsulation.

**Comment by Rishika0101** [comment]
I have implemented it.

**Comment by Rishika0101** [comment]
I have implemented it.

**Comment by Rishika0101** [comment]
worked on comments.

**Comment by Rishika0101** [comment]
I have implemented it.

**Comment by Rishika0101** [comment]
As per your suggestions, I have resolved the conflict successfully.

**Pull request merged**
